# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_connect(object):
    def setupUi(self, widget_connect):
        widget_connect.setObjectName("widget_connect")
        widget_connect.resize(291, 161)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_connect.sizePolicy().hasHeightForWidth())
        widget_connect.setSizePolicy(sizePolicy)
        widget_connect.setMinimumSize(QtCore.QSize(0, 0))
        widget_connect.setMaximumSize(QtCore.QSize(1024, 1024))
        self.formLayoutWidget = QtWidgets.QWidget(widget_connect)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 112))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_lineEdit = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_lineEdit.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_lineEdit.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_lineEdit.setContentsMargins(10, 10, 10, 10)
        self.formLayout_lineEdit.setHorizontalSpacing(11)
        self.formLayout_lineEdit.setVerticalSpacing(20)
        self.formLayout_lineEdit.setObjectName("formLayout_lineEdit")
        self.label_ipv4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_ipv4.setObjectName("label_ipv4")
        self.formLayout_lineEdit.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ipv4)
        self.lineEdit_ipv4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ipv4.setObjectName("lineEdit_ipv4")
        self.formLayout_lineEdit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ipv4)
        self.label_port = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_port.setObjectName("label_port")
        self.formLayout_lineEdit.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.formLayout_lineEdit.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_port)
        self.horizontalLayoutWidget = QtWidgets.QWidget(widget_connect)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 291, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_pushButton = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_pushButton.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_pushButton.setSpacing(9)
        self.horizontalLayout_pushButton.setObjectName("horizontalLayout_pushButton")
        self.pushButton_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_pushButton.addWidget(self.pushButton_connect)
        self.pushButton_exit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_pushButton.addWidget(self.pushButton_exit)

        self.retranslateUi(widget_connect)
        QtCore.QMetaObject.connectSlotsByName(widget_connect)

    def retranslateUi(self, widget_connect):
        _translate = QtCore.QCoreApplication.translate
        widget_connect.setWindowTitle(_translate("widget_connect", "连接"))
        self.label_ipv4.setText(_translate("widget_connect", "IPv4："))
        self.label_port.setText(_translate("widget_connect", "端口："))
        self.pushButton_connect.setText(_translate("widget_connect", "连接"))
        self.pushButton_exit.setText(_translate("widget_connect", "退出"))
