# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Error_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_errorlogin(object):
    def setupUi(self, widget_errorlogin):
        widget_errorlogin.setObjectName("widget_errorlogin")
        widget_errorlogin.resize(291, 161)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_errorlogin.sizePolicy().hasHeightForWidth())
        widget_errorlogin.setSizePolicy(sizePolicy)
        widget_errorlogin.setMinimumSize(QtCore.QSize(0, 0))
        widget_errorlogin.setMaximumSize(QtCore.QSize(1024, 1024))
        self.verticalLayoutWidget = QtWidgets.QWidget(widget_errorlogin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_error = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_error.setContentsMargins(10, 20, 10, 10)
        self.verticalLayout_error.setSpacing(10)
        self.verticalLayout_error.setObjectName("verticalLayout_error")
        self.label_linefirst = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_linefirst.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linefirst.setObjectName("label_linefirst")
        self.verticalLayout_error.addWidget(self.label_linefirst)
        self.label_linesecond = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_linesecond.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linesecond.setObjectName("label_linesecond")
        self.verticalLayout_error.addWidget(self.label_linesecond)
        self.pushButton_ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ok.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_ok.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_error.addWidget(self.pushButton_ok)

        self.retranslateUi(widget_errorlogin)
        QtCore.QMetaObject.connectSlotsByName(widget_errorlogin)

    def retranslateUi(self, widget_errorlogin):
        _translate = QtCore.QCoreApplication.translate
        widget_errorlogin.setWindowTitle(_translate("widget_errorlogin", "错误"))
        self.label_linefirst.setText(_translate("widget_errorlogin", "无法登录到服务器！"))
        self.label_linesecond.setText(_translate("widget_errorlogin", "请检查用户名或密码是否正确。"))
        self.pushButton_ok.setText(_translate("widget_errorlogin", "确定"))
